platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/bosh-lite-spiff
    tag: latest

inputs:
  - name: cf-release-dockerfile
  - name: cf-release-git
outputs:
  - name: manifest

run:
  path: cf-release-dockerfile/ci/tasks/create-manifest/run