---
jobs:
- name: bake-release-uploaded
  public: true
  plan:
  - get: bosh-lite-spiff-dockerhub
    trigger: true
    params:
      save: true
  - get: cf-release
    trigger: true
  - get: manifest
    trigger: true
  - get: bosh-lite-stemcell
    trigger: true
  - get: cf-release-dockerfile
    trigger: true
  - task: compile-release
    file: cf-release-dockerfile/ci/tasks/compile-release/task.yml
    privileged: true
  - put: cf-release-compiled
    params:
      file: cf-release-compiled/release-cf-251-on-ubuntu-trusty-stemcell-3312.15.tgz

- name: use-cf-release-compiled
  public: true
  plan:
  - get: cf-release-compiled
    trigger: true
    passed: [bake-release-uploaded]
  - get: bosh-lite-spiff-dockerhub
    passed: [bake-release-uploaded]
    params:
      save: true
  - get: cf-release
    passed: [bake-release-uploaded]
  - get: manifest
    passed: [bake-release-uploaded]
  - get: bosh-lite-stemcell
    passed: [bake-release-uploaded]
  - get: cf-release-dockerfile
    passed: [bake-release-uploaded]
  - task: deploy-cf
    file: cf-release-dockerfile/ci/tasks/deploy-cf-release-compiled/task.yml
    privileged: true


resources:
- name: cf-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-release

- name: bosh-lite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

- name: cf-release-dockerfile
  type: git
  source:
    uri: https://github.com/EngineerBetter/cf-release-dockerfile.git

- name: bosh-lite-spiff-dockerhub
  type: docker-image
  source:
    repository: engineerbetter/bosh-lite-spiff
    username: {{docker-user}}
    password: {{docker-password}}

# - name: cf-release-dockerhub
#   type: docker-image
#   source:
#     repository: engineerbetter/cf-release
#     username: {{docker-user}}
#     password: {{docker-password}}

- name: cf-release-compiled
  type: s3
  source:
    bucket: bosh-lite-cf-manifests
    region_name: eu-west-1
    versioned_file: release-cf-251-on-ubuntu-trusty-stemcell-3312.15.tgz
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret-key}}

# - name: exported-image
#   type: s3
#   source:
#     bucket: bosh-lite-cf-manifests
#     region_name: eu-west-1
#     versioned_file: release-uploaded.tar.gz
#     access_key_id: {{s3-access-key}}
#     secret_access_key: {{s3-secret-key}}

- name: manifest
  type: s3
  source:
    bucket: bosh-lite-cf-manifests
    region_name: eu-west-1
    versioned_file: cf.yml
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret-key}}