#!/bin/sh

set -ex

source /docker-lib.sh
start_docker

docker load -i bosh-lite-spiff-dockerhub/image
docker tag "$(cat bosh-lite-spiff-dockerhub/image-id)" "$(cat bosh-lite-spiff-dockerhub/repository):$(cat bosh-lite-spiff-dockerhub/tag)"
docker ps
docker images
docker rm bosh || true
docker create --name bosh --privileged engineerbetter/bosh-lite-spiff /usr/bin/start-bosh
docker start bosh
docker cp cf-release/release.tgz bosh:/release.tgz
docker cp bosh-lite-stemcell/stemcell.tgz bosh:/stemcell.tgz
docker cp cf-release-git/ bosh:/cf-release-git
docker exec bosh bosh upload stemcell /stemcell.tgz
docker exec bosh bosh upload release /release.tgz
docker exec bosh /cf-release-git/scripts/generate-bosh-lite-dev-manifest
docker commit bosh engineerbetter/cf-release
