#!/bin/sh

set -ex

source /docker-lib.sh
start_docker

docker load -i bosh-lite-spiff-dockerhub/image
docker tag "$(cat bosh-lite-spiff-dockerhub/image-id)" "$(cat bosh-lite-spiff-dockerhub/repository):$(cat bosh-lite-spiff-dockerhub/tag)"
docker ps
docker images
docker rm bosh || true
docker create --name bosh --privileged engineerbetter/bosh-lite-spiff /usr/bin/start-bosh
docker start bosh
docker cp cf-release/release.tgz bosh:/release.tgz
docker cp bosh-lite-stemcell/stemcell.tgz bosh:/stemcell.tgz
docker cp manifest/cf.yml bosh:/cf.yml
docker exec bosh bosh upload stemcell /stemcell.tgz
docker exec rm -rf /stemcell.tgz
docker exec bosh bosh upload release /release.tgz
docker exec rm -rf /release.tgz
docker exec bosh bosh deployment /cf.yml
docker exec bosh bosh -n deploy
df -h
docker export bosh -o ./deployed.tgz
df -h