#!/bin/bash

set -x

apt-get update
wget -O docker.deb https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.13.0-0~ubuntu-trusty_amd64.deb
dpkg -i docker.deb
rm docker.deb
apt-get -fy install
/etc/init.d/docker start

/usr/bin/start-bosh &
bosh_pid=$!
bosh upload stemcell bosh-lite-stemcell/stemcell.tgz
bosh upload release cf-release-compiled/release-cf-251-on-ubuntu-trusty-stemcell-3312.15.tgz
bosh deployment manifest/cf.yml
bosh -n deploy
bosh vms
curl http://api.bosh-lite.com/v2/info

docker create --name tests --privileged maven/3.3.9-jdk-8-alpine --env CF_USERNAME=admin --env CF_PASSWORD=admin --env CF_HOST=api.bosh-lite.com
docker cp cf-converger/. tests:/tests/
docker run --privileged  cd /tests/ && mvn verify
killall runsvdir-start