#!/bin/sh

set -ex

source /docker-lib.sh
start_docker

mkdir -p test
touch test.txt

docker load -i bosh-lite-spiff-dockerhub/image
docker tag "$(cat bosh-lite-spiff-dockerhub/image-id)" "$(cat bosh-lite-spiff-dockerhub/repository):$(cat bosh-lite-spiff-dockerhub/tag)"
docker ps
docker images
docker rm bosh || true
docker create --name bosh --privileged engineerbetter/bosh-lite-spiff /usr/bin/start-bosh
docker start bosh

docker cp bosh-lite-stemcell/stemcell.tgz bosh:/stemcell.tgz
docker exec bosh bosh upload stemcell /stemcell.tgz
docker exec bosh rm -rf /stemcell.tgz

docker cp cf-release-compiled/release-cf-251-on-ubuntu-trusty-stemcell-3312.15.tgz bosh:/compiled-release.tgz
docker exec bosh bosh upload release /compiled-release.tgz
docker exec bosh rm -rf /compiled-release.tgz

docker cp manifest/cf.yml bosh:/cf.yml
docker exec bosh bosh deployment /cf.yml

docker exec bosh bosh -n deploy

docker exec bosh bosh vms
docker exec bosh curl http://api.bosh-lite.com/v2/info